/**
 * Patches .vc-config.json files generated by @astrojs/vercel to use nodejs20.x.
 *
 * Why this exists: @astrojs/vercel v7 only knows Node 18 and 20 in its support table.
 * When built on Node 22 (which is not in the table) the adapter falls back to "nodejs18.x",
 * but Vercel retired Node 18 in early 2025 and now rejects that runtime string at deploy time.
 *
 * This script runs after `astro build` and rewrites any "nodejs18.x" runtime entry to
 * "nodejs20.x" (the current Vercel LTS default).
 */

import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const FUNCTIONS_DIR = join(ROOT, '.vercel', 'output', 'functions');
const TARGET_RUNTIME = 'nodejs18.x';
const PATCHED_RUNTIME = 'nodejs20.x';

async function walk(dir) {
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    console.error(`patch-runtime: functions directory not found at ${dir}`);
    console.error('  Run `astro build` before this script.');
    process.exit(1);
  }

  const configs = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      configs.push(...await walk(full));
    } else if (entry.name === '.vc-config.json') {
      configs.push(full);
    }
  }
  return configs;
}

const configs = await walk(FUNCTIONS_DIR);
let patched = 0;

for (const configPath of configs) {
  const raw = await readFile(configPath, 'utf-8');
  const obj = JSON.parse(raw);

  if (obj.runtime === TARGET_RUNTIME) {
    obj.runtime = PATCHED_RUNTIME;
    await writeFile(configPath, JSON.stringify(obj, null, '\t'), 'utf-8');
    console.log(`patch-runtime: ${configPath.replace(ROOT, '')}`);
    console.log(`  runtime: "${TARGET_RUNTIME}" → "${PATCHED_RUNTIME}"`);
    patched++;
  }
}

if (patched === 0) {
  console.log(`patch-runtime: no "${TARGET_RUNTIME}" entries found — nothing to patch.`);
} else {
  console.log(`patch-runtime: patched ${patched} config(s).`);
}
